export const sourceGroupIds = [
  "pathways",
  "docs",
  "wwdc",
  "swift",
  "hig",
  "community",
  "forums",
] as const

export type SourceGroupId = (typeof sourceGroupIds)[number]

export type Source = {
  id: string
  title: string
  url: string
  group: SourceGroupId
  publisher: string
  blurb: string
}

export const sourceGroups: {
  id: SourceGroupId
  title: string
  lede: string
}[] = [
  {
    id: "pathways",
    title: "Apple pathways",
    lede: "Apple's own sequenced doors. Start here when you want the official order of videos, tutorials, and tools.",
  },
  {
    id: "docs",
    title: "Apple documentation",
    lede: "The API pages you keep open while you type. When a tutorial and a doc disagree, the current doc wins.",
  },
  {
    id: "wwdc",
    title: "WWDC sessions",
    lede: "The sessions that explain the mental model. Watch one, then return to the sample you are building.",
  },
  {
    id: "swift",
    title: "Swift.org",
    lede: "The language itself, separate from any Apple UI framework. This is the book you return to for syntax.",
  },
  {
    id: "hig",
    title: "Human Interface Guidelines",
    lede: "How an Apple-platform app is supposed to feel. Design choices in this guide point back here.",
  },
  {
    id: "community",
    title: "Courses and field notes",
    lede: "Long practice loops and working notes. Use them to repeat a skill. This guide does not reprint them.",
  },
  {
    id: "forums",
    title: "Forums and release notes",
    lede: "Where the platform moved this year, and where working developers ask when the doc is quiet.",
  },
]

export const sourceList: Source[] = [
  {
    id: "apple-developer-pathway",
    title: "Apple Developer Pathway",
    url: "https://developer.apple.com/pathways/developer/",
    group: "pathways",
    publisher: "Apple",
    blurb: "The free on-ramp: account, Xcode, Swift, SwiftUI, and where to go next.",
  },
  {
    id: "swift-pathway",
    title: "Swift Pathway",
    url: "https://developer.apple.com/swift/get-started/",
    group: "pathways",
    publisher: "Apple",
    blurb: "Apple's sequenced introduction to the language, with pointers into the Swift book.",
  },
  {
    id: "swiftui-pathway",
    title: "SwiftUI Pathway",
    url: "https://developer.apple.com/swiftui/get-started/",
    group: "pathways",
    publisher: "Apple",
    blurb: "Essentials, tutorials, layout, navigation, and data modeling in Apple's order.",
  },
  {
    id: "ios-pathway",
    title: "iOS Pathway",
    url: "https://developer.apple.com/ios/get-started/",
    group: "pathways",
    publisher: "Apple",
    blurb: "How Apple wants a new iOS developer to meet Xcode, SwiftUI, and the HIG.",
  },
  {
    id: "macos-pathway",
    title: "macOS Pathway",
    url: "https://developer.apple.com/macos/get-started/",
    group: "pathways",
    publisher: "Apple",
    blurb: "Windows, scenes, accessibility, and the macOS documentation door.",
  },
  {
    id: "watchos-pathway",
    title: "watchOS Pathway",
    url: "https://developer.apple.com/watchos/get-started/",
    group: "pathways",
    publisher: "Apple",
    blurb: "Apple's starting collection for wrist apps, widgets, and watch documentation.",
  },
  {
    id: "develop-in-swift",
    title: "Develop in Swift Tutorials",
    url: "https://developer.apple.com/tutorials/develop-in-swift",
    group: "pathways",
    publisher: "Apple",
    blurb: "Guided Xcode projects, including views and SwiftData, used in Apple's code-alongs.",
  },
  {
    id: "swiftui-tutorials",
    title: "SwiftUI tutorials",
    url: "https://developer.apple.com/tutorials/swiftui",
    group: "pathways",
    publisher: "Apple",
    blurb: "Apple's hands-on SwiftUI lessons. Do them beside this guide, not instead of typing.",
  },
  {
    id: "xcode",
    title: "Xcode",
    url: "https://developer.apple.com/xcode/",
    group: "docs",
    publisher: "Apple",
    blurb: "The IDE, the current system requirements, and what ships inside the download.",
  },
  {
    id: "swift-playgrounds",
    title: "Swift Playground",
    url: "https://developer.apple.com/swift-playgrounds/",
    group: "docs",
    publisher: "Apple",
    blurb: "A gentler place to learn Swift on Mac or iPad before a full app target.",
  },
  {
    id: "swiftui",
    title: "SwiftUI",
    url: "https://developer.apple.com/documentation/swiftui",
    group: "docs",
    publisher: "Apple",
    blurb: "The framework reference for views, scenes, and state across every Apple platform.",
  },
  {
    id: "swiftdata",
    title: "SwiftData",
    url: "https://developer.apple.com/documentation/swiftdata",
    group: "docs",
    publisher: "Apple",
    blurb: "Model classes, containers, and queries for data that survives a relaunch.",
  },
  {
    id: "model-data",
    title: "Managing model data in your app",
    url: "https://developer.apple.com/documentation/swiftui/managing-model-data-in-your-app",
    group: "docs",
    publisher: "Apple",
    blurb: "How SwiftUI expects you to connect a model to views.",
  },
  {
    id: "observation",
    title: "Observation",
    url: "https://developer.apple.com/documentation/observation",
    group: "docs",
    publisher: "Apple",
    blurb: "The @Observable macro and why views update when specific properties change.",
  },
  {
    id: "swift-concurrency",
    title: "Swift concurrency",
    url: "https://developer.apple.com/documentation/swift/concurrency",
    group: "docs",
    publisher: "Apple",
    blurb: "Tasks, actors, and the main actor as Apple documents them for app code.",
  },
  {
    id: "urlsession",
    title: "URLSession",
    url: "https://developer.apple.com/documentation/foundation/urlsession",
    group: "docs",
    publisher: "Apple",
    blurb: "The networking type you use to fetch JSON without blocking the interface.",
  },
  {
    id: "user-notifications",
    title: "User Notifications",
    url: "https://developer.apple.com/documentation/usernotifications",
    group: "docs",
    publisher: "Apple",
    blurb: "Permission, local notifications, and the system that delivers them.",
  },
  {
    id: "photos-picker",
    title: "Photos picker in SwiftUI",
    url: "https://developer.apple.com/documentation/photokit/bringing-photos-picker-to-your-swiftui-app",
    group: "docs",
    publisher: "Apple",
    blurb: "Let people choose photos without taking broad library access.",
  },
  {
    id: "localization",
    title: "Localization",
    url: "https://developer.apple.com/documentation/xcode/localization",
    group: "docs",
    publisher: "Apple",
    blurb: "String catalogs and how Xcode exports the words in your interface.",
  },
  {
    id: "accessibility",
    title: "Accessibility",
    url: "https://developer.apple.com/documentation/accessibility",
    group: "docs",
    publisher: "Apple",
    blurb: "Labels, traits, and the APIs VoiceOver and other assistive tech read.",
  },
  {
    id: "xctest",
    title: "XCTest",
    url: "https://developer.apple.com/documentation/xctest",
    group: "docs",
    publisher: "Apple",
    blurb: "Unit tests and UI tests that run inside Xcode.",
  },
  {
    id: "instruments",
    title: "Improving your app's performance",
    url: "https://developer.apple.com/documentation/xcode/improving-your-app-s-performance",
    group: "docs",
    publisher: "Apple",
    blurb: "Where Apple points you once a hunch about slowness is not enough.",
  },
  {
    id: "widgetkit",
    title: "WidgetKit",
    url: "https://developer.apple.com/documentation/widgetkit",
    group: "docs",
    publisher: "Apple",
    blurb: "Home Screen widgets, Lock Screen accessories, and watch complications.",
  },
  {
    id: "app-intents",
    title: "App Intents",
    url: "https://developer.apple.com/documentation/appintents",
    group: "docs",
    publisher: "Apple",
    blurb: "Actions the system can run from Shortcuts, Spotlight, and Siri.",
  },
  {
    id: "sf-symbols",
    title: "SF Symbols",
    url: "https://developer.apple.com/sf-symbols/",
    group: "docs",
    publisher: "Apple",
    blurb: "The system icon set. Use it before you draw a custom glyph.",
  },
  {
    id: "navigation",
    title: "Navigation",
    url: "https://developer.apple.com/documentation/swiftui/navigation",
    group: "docs",
    publisher: "Apple",
    blurb: "Stacks, links, split views, and the current navigation APIs.",
  },
  {
    id: "list",
    title: "List",
    url: "https://developer.apple.com/documentation/swiftui/list",
    group: "docs",
    publisher: "Apple",
    blurb: "The scrolling container SwiftUI adapts per platform.",
  },
  {
    id: "app-review",
    title: "App Review Guidelines",
    url: "https://developer.apple.com/app-store/review/guidelines/",
    group: "docs",
    publisher: "Apple",
    blurb: "The rules a binary has to satisfy before it stays on the store.",
  },
  {
    id: "privacy-manifest",
    title: "Privacy manifest files",
    url: "https://developer.apple.com/documentation/bundleresources/privacy-manifest-files",
    group: "docs",
    publisher: "Apple",
    blurb: "The privacy report Apple expects inside modern app bundles.",
  },
  {
    id: "testflight",
    title: "TestFlight",
    url: "https://developer.apple.com/testflight/",
    group: "docs",
    publisher: "Apple",
    blurb: "How other people install a build before the public release.",
  },
  {
    id: "distribution",
    title: "Distributing your app",
    url: "https://developer.apple.com/documentation/xcode/distributing-your-app-for-beta-testing-and-releases",
    group: "docs",
    publisher: "Apple",
    blurb: "Archives, export, TestFlight, and store upload from Xcode.",
  },
  {
    id: "packages",
    title: "Swift packages",
    url: "https://www.swift.org/documentation/package-manager/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "How a package is laid out when you split an app into modules.",
  },
  {
    id: "appkit",
    title: "AppKit",
    url: "https://developer.apple.com/documentation/appkit",
    group: "docs",
    publisher: "Apple",
    blurb: "The older Mac UI framework you still meet when SwiftUI has no equivalent.",
  },
  {
    id: "uikit",
    title: "UIKit",
    url: "https://developer.apple.com/documentation/uikit",
    group: "docs",
    publisher: "Apple",
    blurb: "The iPhone framework older courses still use. Read it when a sample is not SwiftUI.",
  },
  {
    id: "sandbox",
    title: "App Sandbox",
    url: "https://developer.apple.com/documentation/security/app-sandbox",
    group: "docs",
    publisher: "Apple",
    blurb: "The container a Mac App Store app is required to live inside.",
  },
  {
    id: "notarization",
    title: "Notarizing macOS software",
    url: "https://developer.apple.com/documentation/security/notarizing-macos-software-before-distribution",
    group: "docs",
    publisher: "Apple",
    blurb: "The check Apple runs before a Mac outside the store will open your app calmly.",
  },
  {
    id: "document-group",
    title: "DocumentGroup",
    url: "https://developer.apple.com/documentation/swiftui/documentgroup",
    group: "docs",
    publisher: "Apple",
    blurb: "SwiftUI's scene for document-based Mac and iPad apps.",
  },
  {
    id: "menu-bar-extra",
    title: "MenuBarExtra",
    url: "https://developer.apple.com/documentation/swiftui/menubarextra",
    group: "docs",
    publisher: "Apple",
    blurb: "A SwiftUI scene that lives in the macOS menu bar.",
  },
  {
    id: "table",
    title: "Table",
    url: "https://developer.apple.com/documentation/swiftui/table",
    group: "docs",
    publisher: "Apple",
    blurb: "Rows and columns for Mac, with selection and sorting.",
  },
  {
    id: "commands",
    title: "Commands",
    url: "https://developer.apple.com/documentation/swiftui/commands",
    group: "docs",
    publisher: "Apple",
    blurb: "Menu commands and keyboard shortcuts in a SwiftUI app.",
  },
  {
    id: "settings",
    title: "Settings",
    url: "https://developer.apple.com/documentation/swiftui/settings",
    group: "docs",
    publisher: "Apple",
    blurb: "The scene that becomes Settings on the Mac and a preferences surface elsewhere.",
  },
  {
    id: "transferable",
    title: "Transferable",
    url: "https://developer.apple.com/documentation/coretransferable/transferable",
    group: "docs",
    publisher: "Apple",
    blurb: "The protocol drag and drop and share sheets use to move your types.",
  },
  {
    id: "scene",
    title: "Scene",
    url: "https://developer.apple.com/documentation/swiftui/scene",
    group: "docs",
    publisher: "Apple",
    blurb: "Windows, settings, and menu-bar extras are all scenes.",
  },
  {
    id: "nsview-representable",
    title: "NSViewRepresentable",
    url: "https://developer.apple.com/documentation/swiftui/nsviewrepresentable",
    group: "docs",
    publisher: "Apple",
    blurb: "Wrap an AppKit view when SwiftUI cannot express it.",
  },
  {
    id: "uiview-representable",
    title: "UIViewRepresentable",
    url: "https://developer.apple.com/documentation/swiftui/uiviewrepresentable",
    group: "docs",
    publisher: "Apple",
    blurb: "Wrap a UIKit view inside SwiftUI on iPhone.",
  },
  {
    id: "watchos-home",
    title: "watchOS",
    url: "https://developer.apple.com/watchos/",
    group: "docs",
    publisher: "Apple",
    blurb: "The product page for current watch capabilities, including the design and Smart Stack.",
  },
  {
    id: "watchos-docs",
    title: "watchOS apps",
    url: "https://developer.apple.com/documentation/watchos-apps",
    group: "docs",
    publisher: "Apple",
    blurb: "The documentation hub for life cycle, complications, and watch UI.",
  },
  {
    id: "building-watch",
    title: "Building a watchOS app",
    url: "https://developer.apple.com/documentation/watchos-apps/building_a_watchos_app",
    group: "docs",
    publisher: "Apple",
    blurb: "The life cycle article: App, scenes, and WKApplicationDelegateAdaptor.",
  },
  {
    id: "independent-watch",
    title: "Creating independent watchOS apps",
    url: "https://developer.apple.com/documentation/watchos-apps/creating-independent-watchos-apps",
    group: "docs",
    publisher: "Apple",
    blurb: "When the watch app does not require the iPhone companion to be installed.",
  },
  {
    id: "timelines",
    title: "Updating watchOS apps with timelines",
    url: "https://developer.apple.com/documentation/watchos-apps/updating-watchos-apps-with-timelines",
    group: "docs",
    publisher: "Apple",
    blurb: "How TimelineView keeps Always On honest without a spinning timer.",
  },
  {
    id: "timelineview",
    title: "TimelineView",
    url: "https://developer.apple.com/documentation/swiftui/timelineview",
    group: "docs",
    publisher: "Apple",
    blurb: "The SwiftUI view that asks for content at scheduled dates.",
  },
  {
    id: "watch-connectivity",
    title: "Watch Connectivity",
    url: "https://developer.apple.com/documentation/watchconnectivity",
    group: "docs",
    publisher: "Apple",
    blurb: "Messages and context between a paired iPhone and its watch.",
  },
  {
    id: "healthkit",
    title: "HealthKit",
    url: "https://developer.apple.com/documentation/healthkit",
    group: "docs",
    publisher: "Apple",
    blurb: "The store for health samples, workouts, and the permission model around them.",
  },
  {
    id: "health-privacy",
    title: "Protecting user privacy",
    url: "https://developer.apple.com/documentation/healthkit/protecting-user-privacy",
    group: "docs",
    publisher: "Apple",
    blurb: "What you may do with health data, and what the guidelines forbid.",
  },
  {
    id: "health-auth",
    title: "Authorizing access to health data",
    url: "https://developer.apple.com/documentation/healthkit/authorizing-access-to-health-data",
    group: "docs",
    publisher: "Apple",
    blurb: "The capability, the usage strings, and the request API.",
  },
  {
    id: "hkworkout",
    title: "HKWorkout",
    url: "https://developer.apple.com/documentation/healthkit/hkworkout",
    group: "docs",
    publisher: "Apple",
    blurb: "The sample that represents one workout and the samples attached to it.",
  },
  {
    id: "clockkit-migration",
    title: "Migrating ClockKit complications to WidgetKit",
    url: "https://developer.apple.com/documentation/widgetkit/converting-a-clockkit-app",
    group: "docs",
    publisher: "Apple",
    blurb: "Complications are WidgetKit accessories now. This is the migration map.",
  },
  {
    id: "background-tasks",
    title: "Background Tasks",
    url: "https://developer.apple.com/documentation/backgroundtasks",
    group: "docs",
    publisher: "Apple",
    blurb: "Scheduled refresh and processing time the system may grant an iPhone app.",
  },
  {
    id: "digital-crown",
    title: "digitalCrownRotation",
    url: "https://developer.apple.com/documentation/swiftui/view/digitalcrownrotation(_:)",
    group: "docs",
    publisher: "Apple",
    blurb: "Bind a value to the Digital Crown instead of inventing a tiny slider.",
  },
  {
    id: "entitlements",
    title: "Entitlements",
    url: "https://developer.apple.com/documentation/bundleresources/entitlements",
    group: "docs",
    publisher: "Apple",
    blurb: "The capabilities you declare, from HealthKit to the App Sandbox.",
  },
  {
    id: "signing",
    title: "Certificates, identifiers, and profiles",
    url: "https://developer.apple.com/help/account/certificates",
    group: "docs",
    publisher: "Apple",
    blurb: "The membership help for the signing objects a paid account creates.",
  },
  {
    id: "swift-org",
    title: "Swift.org",
    url: "https://www.swift.org/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "The language project: downloads, evolution, and the blog.",
  },
  {
    id: "swift-book",
    title: "The Swift Programming Language",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "The book. When this guide names a feature, the chapter is the full account.",
  },
  {
    id: "swift-tour",
    title: "A Swift Tour",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/guidedtour/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "A single chapter that walks through the syntax you will use every day.",
  },
  {
    id: "swift-basics",
    title: "The Basics",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/thebasics/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "Constants, variables, types, optionals, and assertions.",
  },
  {
    id: "swift-collections",
    title: "Collection Types",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/collectiontypes/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "Arrays, sets, and dictionaries.",
  },
  {
    id: "swift-functions",
    title: "Functions",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/functions/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "Parameters, returns, and argument labels.",
  },
  {
    id: "swift-closures",
    title: "Closures",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/closures/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "Functions you can pass, and the shorthand Swift actually uses.",
  },
  {
    id: "swift-structures",
    title: "Structures and Classes",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/classesandstructures/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "Value types, reference types, and identity.",
  },
  {
    id: "swift-protocols",
    title: "Protocols",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/protocols/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "Requirements you can adopt, extend, and use as types.",
  },
  {
    id: "swift-errors",
    title: "Error Handling",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/errorhandling/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "throw, try, and do/catch.",
  },
  {
    id: "swift-generics",
    title: "Generics",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/generics/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "Code that keeps its types without copying the function.",
  },
  {
    id: "swift-concurrency-book",
    title: "Concurrency",
    url: "https://docs.swift.org/latest/documentation/the-swift-programming-language/concurrency/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "The language chapter for async, await, and actors.",
  },
  {
    id: "api-design",
    title: "API Design Guidelines",
    url: "https://www.swift.org/documentation/api-design-guidelines/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "How Swift names are supposed to read at the call site.",
  },
  {
    id: "swift-blog",
    title: "Swift blog",
    url: "https://www.swift.org/blog/",
    group: "swift",
    publisher: "Swift.org",
    blurb: "Language release notes from the Swift project itself.",
  },
  {
    id: "hig",
    title: "Human Interface Guidelines",
    url: "https://developer.apple.com/design/human-interface-guidelines",
    group: "hig",
    publisher: "Apple Design",
    blurb: "The design system index for every Apple platform.",
  },
  {
    id: "hig-ios",
    title: "Designing for iOS",
    url: "https://developer.apple.com/design/human-interface-guidelines/designing-for-ios",
    group: "hig",
    publisher: "Apple Design",
    blurb: "Layout, navigation, and input expectations on iPhone.",
  },
  {
    id: "hig-macos",
    title: "Designing for macOS",
    url: "https://developer.apple.com/design/human-interface-guidelines/designing-for-macos",
    group: "hig",
    publisher: "Apple Design",
    blurb: "Windows, menus, and pointer-and-keyboard behavior.",
  },
  {
    id: "hig-watch",
    title: "Designing for watchOS",
    url: "https://developer.apple.com/design/human-interface-guidelines/designing-for-watchos",
    group: "hig",
    publisher: "Apple Design",
    blurb: "Glanceable layout, complications, and sessions measured in seconds.",
  },
  {
    id: "hig-layout",
    title: "Layout",
    url: "https://developer.apple.com/design/human-interface-guidelines/layout",
    group: "hig",
    publisher: "Apple Design",
    blurb: "Spacing, safe areas, and how layout adapts.",
  },
  {
    id: "hig-accessibility",
    title: "Accessibility in the HIG",
    url: "https://developer.apple.com/design/human-interface-guidelines/accessibility",
    group: "hig",
    publisher: "Apple Design",
    blurb: "Design guidance for assistive technologies, beyond the API list.",
  },
  {
    id: "design-resources",
    title: "Design resources",
    url: "https://developer.apple.com/design/resources/",
    group: "hig",
    publisher: "Apple Design",
    blurb: "Templates and the Apple Design workbook Apple's pathways recommend.",
  },
  {
    id: "wwdc-swiftui-essentials",
    title: "SwiftUI essentials",
    url: "https://developer.apple.com/videos/play/wwdc2024/10150/",
    group: "wwdc",
    publisher: "WWDC24",
    blurb: "Views, state, and layout from the SwiftUI team. The session this guide assumes you will watch.",
  },
  {
    id: "wwdc-demystify",
    title: "Demystify SwiftUI",
    url: "https://developer.apple.com/videos/play/wwdc2021/10022/",
    group: "wwdc",
    publisher: "WWDC21",
    blurb: "What SwiftUI sees when it looks at your view code: identity, lifetime, and dependencies.",
  },
  {
    id: "wwdc-observation",
    title: "Discover Observation in SwiftUI",
    url: "https://developer.apple.com/videos/play/wwdc2023/10149/",
    group: "wwdc",
    publisher: "WWDC23",
    blurb: "Why new model types use @Observable.",
  },
  {
    id: "wwdc-navigation-cookbook",
    title: "The SwiftUI cookbook for navigation",
    url: "https://developer.apple.com/videos/play/wwdc2022/10054/",
    group: "wwdc",
    publisher: "WWDC22",
    blurb: "Stacks, columns, and sheets, chosen to match the task.",
  },
  {
    id: "wwdc-async",
    title: "Meet async/await in Swift",
    url: "https://developer.apple.com/videos/play/wwdc2021/10132/",
    group: "wwdc",
    publisher: "WWDC21",
    blurb: "The session that introduced the concurrency syntax you write now.",
  },
  {
    id: "wwdc-swiftui-mac",
    title: "SwiftUI on the Mac: Build the fundamentals",
    url: "https://developer.apple.com/videos/play/wwdc2021/10062/",
    group: "wwdc",
    publisher: "WWDC21",
    blurb: "A code-along for sidebar, table, search, toolbar, and multiple windows.",
  },
  {
    id: "wwdc-watchos-26",
    title: "What's new in watchOS 26",
    url: "https://developer.apple.com/videos/play/wwdc2025/334/",
    group: "wwdc",
    publisher: "WWDC25",
    blurb: "arm64 watches, the design update, controls, and Smart Stack changes.",
  },
  {
    id: "wwdc-beginners",
    title: "SwiftUI for Beginners Group Lab",
    url: "https://developer.apple.com/videos/play/wwdc2026/8002/",
    group: "wwdc",
    publisher: "WWDC26",
    blurb: "The SwiftUI team on how to learn: small apps, state, and the official tutorials.",
  },
  {
    id: "wwdc-workout",
    title: "Build a workout app for Apple Watch",
    url: "https://developer.apple.com/videos/play/wwdc2021/10009/",
    group: "wwdc",
    publisher: "WWDC21",
    blurb: "The code-along for HKWorkoutSession, live metrics, and Always On.",
  },
  {
    id: "wwdc-codealong",
    title: "Code-along: Start building with Swift and SwiftUI",
    url: "https://developer.apple.com/videos/play/meet-with-apple/237/",
    group: "wwdc",
    publisher: "Meet with Apple",
    blurb: "A paced build that uses the Develop in Swift tutorials and SwiftData.",
  },
  {
    id: "hws-learn",
    title: "Hacking with Swift",
    url: "https://www.hackingwithswift.com/learn",
    group: "community",
    publisher: "Paul Hudson",
    blurb: "Free paths: 100 Days of SwiftUI, Swift in Sixty Seconds, and a large technique index.",
  },
  {
    id: "hws-100",
    title: "100 Days of SwiftUI",
    url: "https://www.hackingwithswift.com/100/swiftui",
    group: "community",
    publisher: "Hacking with Swift",
    blurb: "The best free repetition loop after this guide's iPhone track. Do the projects in order.",
  },
  {
    id: "hws-sixty",
    title: "Swift in Sixty Seconds",
    url: "https://www.hackingwithswift.com/sixty",
    group: "community",
    publisher: "Hacking with Swift",
    blurb: "One-minute syntax reviews when a foundation lesson needs a second pass.",
  },
  {
    id: "stanford",
    title: "Stanford CS193p",
    url: "https://cs193p.stanford.edu/",
    group: "community",
    publisher: "Stanford University",
    blurb: "Paul Hegarty's course. Watch a recent SwiftUI year and build the assignments yourself.",
  },
  {
    id: "kodeco",
    title: "Kodeco iOS and Swift",
    url: "https://www.kodeco.com/ios",
    group: "community",
    publisher: "Kodeco",
    blurb: "Structured paths and articles. Useful when you want a second explanation of one API.",
  },
  {
    id: "sundell",
    title: "Swift by Sundell",
    url: "https://www.swiftbysundell.com/",
    group: "community",
    publisher: "John Sundell",
    blurb: "Short, precise articles on language and app structure. Read them once you can already build.",
  },
  {
    id: "class-central",
    title: "Best Swift courses, surveyed",
    url: "https://www.classcentral.com/report/best-swift-courses/",
    group: "community",
    publisher: "Class Central",
    blurb: "A map of public courses, with workload notes, if you want a companion class.",
  },
  {
    id: "apple-forums",
    title: "Apple Developer Forums",
    url: "https://developer.apple.com/forums/",
    group: "forums",
    publisher: "Apple",
    blurb: "Questions tagged by framework. Search before you post, and include a minimal sample.",
  },
  {
    id: "swift-forums",
    title: "Swift Forums",
    url: "https://forums.swift.org/",
    group: "forums",
    publisher: "Swift.org",
    blurb: "Language evolution and compiler questions that are not about App Store review.",
  },
  {
    id: "updates",
    title: "Documentation updates",
    url: "https://developer.apple.com/documentation/updates",
    group: "forums",
    publisher: "Apple",
    blurb: "The rolling list of what Apple changed in the docs.",
  },
  {
    id: "ios-release-notes",
    title: "iOS release notes",
    url: "https://developer.apple.com/documentation/ios-ipados-release-notes",
    group: "forums",
    publisher: "Apple",
    blurb: "Read these each year before you adopt a new iOS SDK.",
  },
  {
    id: "macos-release-notes",
    title: "macOS release notes",
    url: "https://developer.apple.com/documentation/macos-release-notes",
    group: "forums",
    publisher: "Apple",
    blurb: "The yearly Mac delta: windows, sandbox, and system features.",
  },
  {
    id: "watchos-release-notes",
    title: "watchOS release notes",
    url: "https://developer.apple.com/documentation/watchos-release-notes",
    group: "forums",
    publisher: "Apple",
    blurb: "The yearly wrist delta, including architecture and API changes.",
  },
]

const byId = new Map(sourceList.map((source) => [source.id, source]))

if (byId.size !== sourceList.length) {
  throw new Error("Duplicate source id in the catalog")
}

export function getSource(id: string): Source {
  const source = byId.get(id)
  if (!source) {
    throw new Error(`Unknown source id: ${id}`)
  }
  return source
}

export function sourcesInGroup(group: SourceGroupId): Source[] {
  return sourceList.filter((source) => source.group === group)
}
